---
title: "Lab 8 Andrew Martinez"
format:
 html:
  code-fold: true
  self-contained: true
editor: visual
---

## Datasets/Libraries/Helper Functions Created In PA8

```{r}
#| include: false
library(dplyr)
library(glue)
library(stringr)
library(purrr)
xmas <- read.csv("https://www.dropbox.com/s/e584pryn8evm1gz/xmas.csv?dl=1")

pluralize_gift <- function(gift){
  gift <- case_when(
    str_detect(gift, "oo") ~ str_replace(gift, "oo", "ee"),
    str_detect(gift, "y$") ~ str_replace(gift, "y", "ies"),
    TRUE ~ str_c(gift, "s", sep = "")
    
  )
return(gift)

}

make_phrase <- function(num_word, item, verb, adjective, location) {

  verb <- str_replace_na(verb, "")
  adjective <- str_replace_na(adjective, "")
  location <- str_replace_na(location, "")
  
    item <- case_when(
    num_word != "one" ~ pluralize_gift(item),
    str_detect(item, "^(a|e|i|o|u|A|E|I|O|U)") == TRUE ~ str_c("an ", item),
    TRUE ~ item)
    
  if(num_word == "one"){ 
    num_word = "a "}

  glue_phrase = glue::glue("{num_word} {adjective} {item} {verb} {location}")
  return(str_squish(glue_phrase))
}
```

```{r}
xmas2 <- xmas %>%
  mutate(day.num = as.character(english::english(Day)
                                ), 
    Full.Phrase = pmap_chr(
      list(
           num_word = day.num,
           item = Gift.Item,
           verb = Verb,
           adjective = Adjective,
           location = Location),
      make_phrase
      )
  )
```

## Step 3

```{r}
# Produces the string for one day of the song.
# Arguments -- dataset -- A data frame containing information about gifts
# Arguments -- line -- The number of the line for the day you want to sing about
# Arguments -- phrase_col -- The variable name for the column in the dataset that contains the song phrases
# Return -- A string singing the line of the song with all gifts for the given day.



sing_day <- function(dataset, line, phrase_col){
  
  # Step 1: Setup the intro line
  num_word <- english::ordinal(line)
  
  intro <- 
    glue::glue("On the {num_word} day of Christmas, my true love gave to me:")
  
  # Step 2: Sing the gift phrases

    phrases <- dataset |>
      pull( {{phrase_col}} )
    phrases_day <- glue_collapse(phrases[line:1], sep = " \n", last = " and \n")
    phrases_day <- str_c(phrases_day, "\n")
    phrases_end <- glue::glue("{intro} \n {phrases_day}")
    
    
  ## put it together
    return(phrases_end)

}

```

## A Smaller Test

```{r}
xmas2 |>
sing_day(line = 2, phrase_col = Full.Phrase)
```

## A Larger Test

```{r}
map_chr(1:12, ~ sing_day(xmas2, .x, Full.Phrase)) |>
  str_c(collapse = "\n") |>
  cat()
```

## Step 4

```{r}
xmas2 <- xmas |>
  mutate(
    day.num = as.character(english::english(Day)), 
    Full.Phrase = pmap_chr(.l = list(num_word = day.num, 
                                     item = Gift.Item, 
                                     verb = Verb, 
                                     adjective = Adjective, 
                                     location = Location), 
                           .f = make_phrase)
  )

map_chr(1:12, ~sing_day(xmas2, .x, Full.Phrase)) |>
  str_c(collapse = "\n") |>
  cat()
```
