---
title: "Lab 5"
format:
  html:
    code-fold: true
editor: visual
---

## Loading In Lab 2 Data / Packages

```{r}
#| message = FALSE
library(tidyverse)
library(forcats)
library(stringr)
surveys <- read.csv(here::here("supporting_artifacts", "Lab & Challenge 2", 
                              "surveys.csv"), 
                   stringsAsFactors = FALSE)

```

## Unedited Lab 2 Graph

```{r}
ggplot(data = surveys, mapping = aes( x = weight, 
                                      y = species)) + 
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(color = "tomato", 
              alpha = 1/50) +
  labs(title = "Distribution Of Weight (In Grams) By Species", 
       x = "Weight (Grams)",
       y = "Species") +
  theme(plot.title = element_text(hjust = .5))
```

## Reordered Lab 2 Graph

```{r}
ggplot(data = surveys, mapping = aes( x = weight, 
                                      y =  fct_reorder(species, 
                                                       weight, 
                                                       .desc = TRUE))) + 
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(color = "tomato", 
              alpha = 1/50) +
  labs(title = "Species", 
       x = "Weight (Grams)",
       y = " ") +
  theme(plot.title = element_text(hjust = .5))
```

## Time Series Plot 1

```{r}
ggplot(data = surveys, mapping = aes(x = weight, 
                                     y = date)) +
  geom_point()
```

## Time Series Plot 2

```{r}
time_series_surveys <- surveys |> 
  separate(col=date, into=c('Year', 'Month', "Day"), sep='-') |> 
  group_by(year, genus) |> 
  mutate(avg_weight = mean(weight))

ggplot(data = time_series_surveys, mapping = aes(x = avg_weight, 
                                     y = Year,
                                     color = fct_reorder(genus, 
                                                       weight, 
                                                       .desc = TRUE))) +
  geom_point()+
  labs(title = "Year", 
       x = "Average Weight (Grams)",
       y = " ",
       color = "Genus") +
  theme(plot.title = element_text(hjust = .5))
```

## Time Series Plots By Week

```{r}
#| message: FALSE
#| warning: false
time_series_surveys_by_week_count <- surveys |> 
  count(day_of_week)

ggplot(data = time_series_surveys_by_week_count, mapping = aes(day_of_week, n))+
  geom_point()+
  labs(y = "Number Of Rodents Caught")
  
  
  
  
```

## Time Series Plot #2

```{r}
time_series_surveys_by_week_count <- surveys |> 
  count(day_of_week) |> 
  filter(day_of_week != "NA")

ggplot(data = time_series_surveys_by_week_count, mapping = aes(
  fct_relevel(day_of_week, c("Mon","Tue","Wed","Thu","Fri","Sat","Sun"))
  , n))+
  geom_point()+
  labs(y = "Number Of Rodents Caught",
       x = "Day Of Week")
```

## Time Series Plot #3

```{r}

time_series_surveys_by_week_count <- surveys |> 
  count(day_of_week) |> 
  mutate(day_of_week = 
           fct_collapse(day_of_week, 
             Weekend = c("Sat", "Sun"))) |>
  group_by(day_of_week) |> 
  summarise(day_of_week, sum(n)) |> 
  distinct(day_of_week, .keep_all = TRUE) |> 
  filter(day_of_week != "NA")

ggplot(data = time_series_surveys_by_week_count, mapping = aes(
  fct_relevel(day_of_week, c("Mon","Tue","Wed","Thu","Fri","Weekend"))
  , `sum(n)`))+
  geom_point()+
  labs(y = "Number Of Rodents Caught",
       x = "Day Of Week")
```
