---
title: "Lab 5"
format:
  html: 
    code-fold: true
editor: visual
---

## Loading In Lab 2 Data / Packages

```{r}
#| message: false
library(tidyverse)
library(forcats)
library(stringr)
surveys <- read.csv(here::here("supporting_artifacts", "Lab & Challenge 2", 
                              "surveys.csv"), 
                   stringsAsFactors = FALSE)
```

## Unedited Lab 2 Graph

```{r}
ggplot(data = surveys, mapping = aes( x = weight, 
                                      y = species)) + 
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(color = "tomato", alpha = 1/50) +
  labs(title = "Distribution Of Weight (In Grams) By Species", 
       x = "Weight (Grams)",
       y = "Species")
```

## Reordered Lab 2 Graph

```{r}
ggplot(data = surveys, mapping = aes( x = weight, 
                                      y =  fct_reorder(species, 
                                                       weight, 
                                                       .desc = TRUE))) + 
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(color = "tomato", alpha = 1/50) +
  labs(title = "Species", 
       x = "Weight (Grams)",
       y = " ") 
```

## Time Series Plot 1

```{r}
ggplot(data = surveys, mapping = aes(x = date, 
                                     y = weight,
                                     color = genus)) +
  geom_line()
```

## Time Series Plot 2

```{r}
  surveys |> 
  separate(col=date, into=c('Year', 'Month', "Day"), sep='-') |> 
  group_by(Year, genus) |> 
  summarize(avg_weight = mean(weight)) |> 
  ggplot(mapping = aes(x = Year, y = avg_weight, 
                       color =fct_reorder2(genus, Year, avg_weight),
                       group = genus)) +
  geom_line() +
  labs(title = "Average Weight (Grams)", 
       x = "Year",
       y = " ",
       color = "Genus")
```

## Time Series Plots By Week

```{r}

ggplot(data = surveys, mapping = aes(day_of_week))+
  geom_bar()+
  labs(y = "Number Of Rodents Caught")
  
```

## Time Series Plot #2

```{r}
surveys_no_na <- surveys |> 
  filter(day_of_week != "NA")

ggplot(data = surveys_no_na, mapping = aes(
  fct_relevel(day_of_week, c("Mon","Tue","Wed","Thu","Fri","Sat","Sun"))))+
  geom_bar()+
  labs(title = "Number Of Rodents Caught",
       x = "Day Of Week",
       y = "")
```

## Time Series Plot #3

```{r}
time_series_surveys_by_week_count <- surveys |> 
  mutate(day_of_week = 
           fct_collapse(day_of_week, 
             Weekend = c("Sat", "Sun"), 
             Weekdays = c("Mon", "Tue", "Wed", "Thu", "Fri"))) |>
  filter(day_of_week != "NA")

ggplot(data = time_series_surveys_by_week_count, 
       mapping = aes(fct_relevel(day_of_week, c("Weekdays","Weekend"))))+
  geom_bar()+
  labs(title = "Number Of Rodents Caught",
       x = "Day Of Week",
       y = "")
```
