---
title: "Lab 7 Andrew Martinez"
format:
 html:
  code-fold: true
  self-contained: true
editor: visual
---

## Loading In Dataset

```{r}
#| message: false
library(tidyverse)
library(here)
BlackFootFish <- read_csv(here::here("supporting_artifacts", "Lab & Challenge 7", "BlackfootFish.csv"))
```

## Part One

### Task One

```{r}
BlackFootFish |>
  summarize(across(.cols = everything(),
                    .fns = ~sum(is.na(.))))
```

### Task Two

```{r}
#| message: false
BlackFootFish |> 
  mutate(Named_Trips = ifelse(trip == 1, 
                         "Trip 1", 
                         "Trip 2")) |>
  group_by(Named_Trips,year,section) |> 
  summarize(weight = sum(is.na(weight))) |> 
  ggplot(mapping = aes(x = year, y = weight)) +
  geom_col(aes(fill = section), position = "stack") +
  facet_wrap(~Named_Trips) +
  labs(
    title = "Number Of NA Observations (Weight)",
    x = "Weight",
    fill = "Section Of Blackfoot River",
    y = "Year"
  )+
  coord_flip()
```

## Part Two

### Task One

```{r}
rescale_01 <- function(vector1){
  range_vector <- range(vector1)
  numerator <- vector1 - range_vector[1]
  denom <- range_vector[2] - range_vector[1]
  return(numerator/denom)
}
```

### Task Two

```{r}
rescale_01 <- function(vector1){
  stopifnot(is.numeric(vector1), length(vector1) >= 1)
  range_vector <- range(vector1, na.rm = TRUE)
  numerator <- vector1 - range_vector[1]
  denom <- range_vector[2] - range_vector[1]
  return(numerator/denom)
}

```

### Task Three

```{r}
rescale_01(c(1:25, NA))
```

### Task Four

```{r}
#| warning: false
#| message: false
#| layout-ncol: 2

ggplot(data = BlackFootFish, mapping = aes( y = rescale_01(length)))+
  geom_boxplot()
ggplot(data = BlackFootFish, mapping = aes( y = length))+
  geom_boxplot()
```

### Task Five

```{r}
rescale_column <- function(data, variables){
  stopifnot(is.data.frame(data), is.numeric(data$variables))
  data <- data |> 
  mutate(
    across(
      .cols = {{ variables }},
      .fns = rescale_01
    )
  )
  return(data)
}
```

### Task Six

```{r}
rescale_column(BlackFootFish, c(length, weight))
```
