---
title: "Challenge 2: Exploring Rodents With ggplot 2"
author: "Andrew Martinez"
format:
  html:
    code-fold: true
    font-family: Georgia
    self-contained: true
editor: visual
---

```{r setup}
#| message: false
library(RColorBrewer)
library(viridis)
library(ggsci)
library(ggridges)
library(tidyverse)
library(here)
```

# Reading the Data into R

```{r data}
surveys = read.csv(here::here("supporting_artifacts", "Lab & Challenge 2", "surveys.csv"), 
                   stringsAsFactors = FALSE)


```

## Challenge Code 1

```{r}
#| warning: false
ggplot(data = surveys, mapping = aes( x = weight, 
                                      y = species,
                                      color = genus)) + 
  geom_density_ridges() +
  geom_jitter(color = "tomato", alpha = 1/50) +
  labs(title = "Distribution Of Weight (In Grams) By Species", 
       x = "Weight (Grams)",
       y = "Species") +
  theme(plot.title = element_text(hjust = .5))
```

## Challenge Code (2 & 3)

```{r}
cdPalette_grey <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
                    "#0072B2", "#D55E00", "#CC79A7")
ggplot(data = surveys, mapping = aes( x = weight, 
                                      y = species,
                                      color = genus)) + 
  geom_boxplot() +
  labs(title = "Distribution Of Weight (In Grams) By Species", 
       x = "Weight (Grams)",
       y = "Species") +
  theme(plot.title = element_text(hjust = .5)) +
  scale_color_manual(values = cdPalette_grey) +
  annotate("text", y = 2, x = 100, label = "Chaetodipus") +
  annotate("text", y = 12, x = 120, label = "Chaetodipus") +
  annotate("text", y = 10, x = 120, label = "Dipodomys") +
  annotate("text", y = 11, x = 125, label = "Dipodomys") +
  annotate("text", y = 13, x = 250, label = "Dipodomys") +
  annotate("text", y = 1, x = 10, label = "Neotoma") +
  annotate("text", y = 14, x = 85, label = "Onychomys") +
  annotate("text", y = 7, x = 90, label = "Onychomys") +
  annotate("text", y = 4, x = 100, label = "Perognathus") +
  annotate("text", y = 3, x = 100, label = "Peromyscus") +
  annotate("text", y = 8, x = 90, label = "Peromyscus") +
  annotate("text", y = 5, x = 100, label = "Reithrodontomys") +
  annotate("text", y = 9, x = 80, label = "Reithrodontomys") +
  annotate("text", y = 6, x = 170, label = "Sigmodon") +
  theme(legend.position="none")
```
