---
title: "My Growth as a Data Scientist"
format:
 html:
  self-contained: true
  editor: visual
---

To preface this essay I think it is important to not only define what exactly a "data scientist" is, but also what role a data scientist serves. Personally, I would define a data scientist as someone who tells a story with data, in order to generate decision support. For example, a data scientist can analyze consumer data to help drive business decisions and insight. As mentioned previously, the role a data scientist serves is largely for decision support. Decision support, in regards to a data scientist, is the process by which insight and arguments are formulated through data a data scientist will mold and analyze. After reflecting and analyzing the work I have done over the quarter, I believe I have grown as a data scientist both inside and outside of Stat 331. Inside of the class, the labs and challenges serve as great tools for students to develop their data scientist skills. Particularly, I personally really enjoyed challenge four, as it was a great critical thinking exercise. To elaborate, you gave us the option to create our own dataset, which both tests our knowledge of how datasets are formatted, but also tests our ability to generate appropriate data from the internet. As a data scientist, you are hardly ever given clean, easily decipherable data, as it is your job to explore and mold the data into a story. So, having an exercise where students have the opportunity to create their own datasets is a great way to expose us to real-world experiences in the field. Additionally, I felt this exercise is concrete evidence of my growth as a data scientist. While I did not have the time to create a massive dataset, I showed the ability to not only properly format the dataset so I could merge it, but also the critical thinking skills to use Zillow housing prices to populate appropriate data to answer the question posed. Additionally, I also believe Challenge 7 is a great example my growth as a data scientist. Challenge 7 showcases my ability to investigate unfamiliar data, a task common to data scientist, meaning I have the capability to explore and learn about a multitude of data regardless of whether I am familiar about it or not. For example, prior to the assignment, I had no idea what the mean weight and size of certain trouts would be, but I was able to find resources online to help aid me in properly dissecting the BlackFootFish data. Lastly, visualization is integral part of data science, and I believe that many of the visualizations I have produced during the quarter showcase my ability in this sector of data science. In particular, I would point to my Challenge 2 graphs, Lab 7 Task Two Graph, and also my Challenge 7 part three graph. All three of the graph's showcase my ability to effectively visualize data. Specifically, not only do they elude to my ability to interpret, visualize, and present data, but also that I keep the readers in mind while I visualize the data. Arguably the most important aspect of being a data scientist is the ability to articulate your findings in a variety of ways, so having the ability to create quality visualization is imperative. In regards to visualization, it is important to format your plots in a manner that is digestible to an uninformed audience. I specifically picked these graphs as they all include annotations or alterations that will ensure uninformed audiences can still read and interpret these graphs. In particular, the annotations on the challenge 2 graphs help with legibility, the plot in Lab 7 has colors and "reversed formatting" so the Year axis is easier to read, and lastly the challenge 7 plot has a facet grid so you can easily compare within species. Additionally, while it cannot be supported by an artifact within the class, many of the assignments have led me down rabbit holes that have sparked growth as a data scientist outside of class. For instance, many of the labs and challenges have sparked general questions that have lead me to question what a career in data science looks like. As a result of this curiousity, I have thoroughly networked with alumni and professors at Cal Poly to not only question what a career in data science would look like, but also resources I could use now to help jump start my success. These networking meetings have resulted in significant growth in my understanding of what data science is, along with the intuition to understand what attributes and qualities compose a successful data scientist. Lastly, I have learned many resources I can use online, such as Kaggle, textbooks, podcasts, and newsletters to continue my growth as a data scientist.
