---
title: "The Power of Efficiency"
format:
 html:
  self-contained: true
editor: visual
---

## The Power of Efficiency

Within statistical computing, efficiency takes many shapes and forms. To me, efficiency within statistical computing and data science can be described as taking the most effective path to your goal. There have been multiple instances throughout the class where your revisions have opened my ideas to the role efficiency plays within statistical computing. For example, one of your revisions you had for me throughout the quarter was to not create intermediate objects when they are not necessary. In particular, in Lab 4 Part One, Task One I assigned the process to a variable, and printed the variable, rather than just directly outputting the variable. While this may be a small example of improving efficiency, small inefficiencies within your programs add up quickly. One thing I learned is that efficiency within your program and code is not something that will happen overnight, and requires you to experiment with code. Efficiency is something that a coder will gather over time, as they continue to learn more about the coding language they code in. One example of this is within my Lab 7, my code was inefficient as within my Part 2 Task 3 I rewrote the function within the code chunk, although it was defined in the previous code chunk. As mentioned before, although this inefficiency may be small, they quickly add up, especially if you are writing large scale documents or code. As I continue to code in R, inefficiencies like this one will shore up. Additionally, to me efficiency plays a role in visualizing your data as well. Part of having good efficiency in your visualizations means choosing the most effective, while simple visualization for your data. For Lab 5 you mentioned to me that while my plot is not "incorrect," typically a different plot is used for frequencies and plots. I originally chose a scatter plot, but normally a bar plot is used. I believe this is a great example of inefficiency, as while the scatter plot technically works, the bar plot is a simpler more effective option. As I continued to have "a-ha" moments regarding efficiency throughout the quarter I began to understand its importance in the grand scheme of coding. In regards to general coding, efficiency is critical as when you write large-scale programs small inefficiencies that add up over your program will severely hinder the performance of your program. For example, if you have inefficiencies within your code for a video game, the FPS performance of it will take a large hit. To me, inefficiency takes a slightly different definition in regards to statistical computing. As mentioned before with my visualizations, efficiency in statistical computing often has to do with solving or displaying your statistical question with the an effective, simple solution. Because having efficient approaches leads to an effective, simple visualization or solution, it allows you to show your findings more effectively. This leads to a better understanding by your audience, and in turn better decision support. Without efficient visualizations and code, the ability to articulate findings becomes much more difficult, which hinders the ability of a data scientist. Throughout this quarter, I have been reminded the importance of efficiency, as it is a crucial part of good statistical computing and data science work.
